apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-list
spec:
  replicas: 4
  selector:
    matchLabels:
      app: shopping-list
  template:
    metadata:
      labels:
        app: shopping-list
    spec:
      containers:
      - name: shopping-list
        image: molotovhammr/shopping-list-service:latest
        imagePullPolicy: Always
        # resources:
        #   requests:
        #     memory: "100Mi"
        #     cpu: "0.05"
        #   limits:
        #     memory: "256Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 80
