apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "shopping-list-service"
  name: shopping-list-service
spec:
  # type: LoadBalancer
  selector:
    app: shopping-list
  ports:
  - port: 80
    targetPort: 80
