apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "3"
  name: catalogue-service
spec:
  type: LoadBalancer
  selector:
    app: catalogue
  ports:
  - port: 80
    targetPort: 80
