name: kubernetes-catalogue-service

on:
  push:
    branches:
      - main
    paths:
      - './kubernetes/catalogue-service/deployment.yaml'
      - './catalogue-service/**'
      - '.github/workflows/**'

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master 
      uses: actions/checkout@v2
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 grocio-cluster     
    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl apply -f ${{ github.workspace }}/kubernetes/catalogue-service/deployment.yaml  
    - name: Verify deployments
      run: kubectl rollout status deployment/catalogue